# Generated by Django 3.2.4 on 2021-08-25 04:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_list', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='id', unique=True),
        ),
    ]
