# Generated by Django 3.2.4 on 2021-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_list', '0005_alter_stock_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
