# Generated by Django 3.2.4 on 2021-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_list', '0006_query_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='stock_regarding',
            field=models.CharField(default='default', max_length=400),
        ),
    ]
